// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListWebApi.Models;

#nullable disable

namespace ToDoListWebApi.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    partial class ToDoListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ToDoListWebApi.Models.Goal", b =>
                {
                    b.Property<Guid>("NidGoal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("date");

                    b.Property<byte>("GoalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("NidGoal");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Progress", b =>
                {
                    b.Property<Guid>("NidProgress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<short>("ProgressTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("NidProgress");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Schedule", b =>
                {
                    b.Property<Guid>("NidSchedule")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("NidSchedule");

                    b.HasIndex("TaskId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Task", b =>
                {
                    b.Property<Guid>("NidTask")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("TaskStatus")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TaskWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("NidTask");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.User", b =>
                {
                    b.Property<Guid>("NidUser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("NidUser");

                    b.HasIndex(new[] { "Username" }, "IX_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Goal", b =>
                {
                    b.HasOne("ToDoListWebApi.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Goals_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Progress", b =>
                {
                    b.HasOne("ToDoListWebApi.Models.Schedule", "Schedule")
                        .WithMany("Progresses")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_Progresses_Schedules");

                    b.HasOne("ToDoListWebApi.Models.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Progresses_Users");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Schedule", b =>
                {
                    b.HasOne("ToDoListWebApi.Models.Task", "Task")
                        .WithMany("Schedules")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Tasks");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Task", b =>
                {
                    b.HasOne("ToDoListWebApi.Models.Goal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId")
                        .IsRequired()
                        .HasConstraintName("FK_Goals_Tasks");

                    b.HasOne("ToDoListWebApi.Models.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Users");

                    b.Navigation("Goal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Goal", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Schedule", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.Task", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ToDoListWebApi.Models.User", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Progresses");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
